language: php
php:
- 7.1
service:
- mysql
before_script:
- composer install
- composer dump-autoload
- cp .env.travis .env
- php artisan jwt:generate
- php artisan key:generate
- php artisan vendor:publish
- mysql -e 'CREATE DATABASE IF NOT EXISTS jokes ;'
- php artisan migrate
script: phpunit
